### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by edbgt** [BanjoBenjo/todo#27]
- Submit and Taskname should look the same in every Task Editor Activity
- Disable all submit buttons until all information is entered
- Rework button design (enabled/disabled), make design global if possible
- General Design rework

**Comment by edbgt** [comment]
- more colors (maybe do creative brief and moodboard)
- create icons for buttons, push notification and app icon

**Comment by edbgt** [comment]
change SUBMIT to SAVE to make it clearer that user needs to save after editing

**Comment by edbgt** [comment]
scale text

**Comment by edbgt** [comment]
floating tasks on mainpage (barockregel)

**Comment by BanjoBenjo** [comment]
so far so guud
