### ISSUE TITLE
shopping list

### ISSUE THREAD

**Issue by BanjoBenjo** [BanjoBenjo/todo#8]
- clear input field after "adding" article
- changing from name to quantity only possible after closing keyboard

**Comment by edbgt** [comment]
clear input field done

**Comment by edbgt** [comment]
crash when no quantity provided

**Comment by edbgt** [comment]
crash when no quantity done

**Comment by edbgt** [comment]
add checkbox

**Comment by edbgt** [comment]
checkbox done

**Comment by edbgt** [comment]
habe fertig
